import { ServiceType } from '@extension/storage/lib/types/mcp';

export const SERVICE_CAPABILITIES: Record<string, string[]> = {
  [ServiceType.LINKEDIN]: [
    'Networking: Profile view',
    'Networking: Connection request send',
    'Networking: Connection accept / ignore',
    'Networking: Message send',
    'Networking: Message reply',
    'Jobs: Job search',
    'Jobs: Job apply',
    'Jobs: Recruiter messages read',
    'Jobs: Resume upload',
    'Content & Activity: Post create',
    'Content & Activity: Post like / comment / share',
    'Content & Activity: Company page follow',
    'Content & Activity: Notifications check',
  ],
  [ServiceType.GMAIL]: [
    'Email Handling: Inbox check',
    'Email Handling: Email read',
    'Email Handling: Email reply / reply all',
    'Email Handling: Email forward',
    'Email Handling: New email compose',
    'Email Management: Email delete',
    'Email Management: Email archive',
    'Email Management: Label add / remove',
    'Email Management: Star / important mark',
    'Email Management: Attachment upload / download',
  ],
  [ServiceType.WHATSAPP]: [
    'Chats: Message read',
    'Chats: Message send',
    'Chats: Message reply',
    'Groups: Group messages read',
    'Groups: Group message send',
    'Groups: Group mute / unmute',
    'Media: Image / video / document send',
    'Media: Media download',
  ],
  [ServiceType.SLACK]: [
    'Communication: Channel messages read',
    'Communication: Channel message send',
    'Communication: Direct message send / reply',
    'Communication: Thread reply',
    'Workspace Management: Channel join / leave',
    'Workspace Management: Message pin / unpin',
    'Workspace Management: Reminder set',
  ],
  [ServiceType.NOTION]: [
    'Page & Content: Page open',
    'Page & Content: New page create',
    'Page & Content: Text edit',
    'Page & Content: Checklist update',
    'Organization: Page move',
    'Organization: Template use',
    'Organization: Database row add',
  ],
  [ServiceType.TWITTER]: [
    'Feed & Interaction: Feed scroll',
    'Feed & Interaction: Tweet read',
    'Feed & Interaction: Tweet post',
    'Feed & Interaction: Tweet reply',
    'Feed & Interaction: Like / retweet',
    'Discovery: Search',
    'Discovery: Profile follow / unfollow',
  ],
  [ServiceType.CALENDAR]: [
    'Event Management: Event create',
    'Event Management: Event edit',
    'Event Management: Event delete',
    'Event Management: Reminder set',
    'Scheduling: Meeting schedule',
    'Scheduling: Availability check',
  ],
  [ServiceType.DRIVE]: [
    'File Management: File upload',
    'File Management: File download',
    'File Management: Folder create',
    'File Management: File move / rename',
    'Sharing: Share link generate',
    'Sharing: Access permission change',
  ],
  [ServiceType.TRELLO]: [
    'Boards: Board open',
    'Boards: New board create',
    'Cards: Card add',
    'Cards: Card edit',
    'Cards: Card move',
    'Cards: Due date set',
  ],
  [ServiceType.GITHUB]: [
    'Repository & Code: Repository open',
    'Repository & Code: Code browse',
    'Repository & Code: File edit',
    'Collaboration: Pull request create',
    'Collaboration: Pull request read',
  ],
};
